---
- name: 'Fedora :: install dnf-plugins-core'
  package:
    name: 'dnf-plugins-core'
    state: 'present'
  become: yes

- name: 'Fedora :: install Docker RPM repository'
  command: |
    dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: no
  become: yes

- name: 'Fedora :: install Docker'
  package:
    name: '{{ qi_install_docker_docker_package }}'
    state: 'present'
  become: yes

- name: 'Fedora :: start Docker'
  service:
    name: 'docker'
    enabled: yes
    state: 'started'
  become: yes
