---
- name: 'Debian :: install the InfluxData APT key'
  apt_key:
    url: 'https://repos.influxdata.com/influxdb.key'
  become: yes

- name: 'Debian :: install the InfluxData APT repository'
  apt_repository:
    repo: |
      deb https://repos.influxdata.com/debian {{ ansible_distribution_release }} stable
  become: yes
