---
- name: 'build Docker images'
  docker_image:
    name: '{{ item.name }}'
    path: '{{ item.path|default(omit) }}'
    dockerfile: '{{ item.dockerfile|default(omit) }}'
    buildargs: '{{ item.buildargs|default(omit) }}'
  become: yes
  with_items: '{{ qi_docker_compose_images|default([]) }}'

- name: 'build and start Docker containers'
  docker_service:
    project_name: '{{ qi_docker_compose_name|default(omit) }}'
    project_src: '{{ qi_docker_compose_folder }}'
    build: yes
    files: '{{ qi_docker_compose_files }}'
  become: yes

- name: 'prune dangling Docker images'
  shell: 'docker image prune -f'
  become: yes

- name: 'prune dangling Docker volumes'
  shell: 'docker volume prune -f'
  become: yes
