---
- include_tasks: 'distribution-debian.yml'
  when: |
    ansible_distribution == 'Debian'

- include_tasks: 'distribution-ubuntu.yml'
  when: |
    ansible_distribution == 'Ubuntu'

- name: 'start AWS SSM Agent'
  service:
    name: 'amazon-ssm-agent'
    enabled: yes
    state: 'started'
  become: yes

