---
- name: 'Fedora :: remove old versions of Docker'
  package:
    name:
    - container-selinux
    - docker
    - docker-common
    - docker-engine
    - docker-selinux
    state: absent
  become: yes

- name: 'Fedora :: install dnf-plugins-core'
  dnf:
    name: dnf-plugins-core
    state: present
  become: yes

- name: 'Fedora :: install Docker YUM repository'
  command: 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
  args:
    warn: no
  become: yes

- name: 'Fedora :: install Docker'
  package:
    name: '{{ qi_docker_package|default("docker-ce") }}'
    state: present
  become: yes

- name: 'Fedora :: start Docker'
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- include: docker-virtualenv.yml
