---
- name: 'Ubuntu :: remove old versions of Docker'
  package:
    name:
    - docker
    - docker-engine
    state: absent
  become: yes

- name: 'Ubuntu :: update APT cache'
  apt:
    update_cache: yes
  become: yes

- name: 'Ubuntu :: install apt-transport-https, ca-certificates, linux-image-extra, and linux-image-extra-virtual'
  package:
    name:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'linux-image-extra-{{ ansible_kernel }}'
    - 'linux-image-extra-virtual'
    state: present
  become: yes

- name: 'Ubuntu :: install Docker APT key via Ansible apt_key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
  become: yes
  when: ansible_distribution_version|version_compare('16.04', '>=')

- name: 'Ubuntu :: install curl'
  package:
    name: 'curl'
    state: present
  become: yes
  when: ansible_distribution_version|version_compare('16.04', '<')

- name: 'Ubuntu :: install Docker APT key via curl'
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
  args:
    warn: no
  become: yes
  when: ansible_distribution_version|version_compare('16.04', '<')

- name: 'Ubuntu :: install Docker APT repository'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
  become: yes

- name: 'Ubuntu :: install Docker'
  apt:
    name: '{{ qi_docker_package|default("docker-ce") }}'
    state: present
    update_cache: yes
  become: yes

- name: 'Ubuntu :: start Docker'
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- include: docker-virtualenv.yml
