---
- name: 'CentOS/RedHat :: remove old versions of Docker'
  package:
    name:
    - docker
    - docker-common
    - docker-engine
    state: absent
  become: yes

- name: 'CentOS/RedHat :: install yum-utils'
  package:
    name: yum-utils
    state: present
  become: yes

- name: 'CentOS/RedHat :: install Docker YUM repository'
  command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
  become: yes

- name: 'CentOS/RedHat :: install Docker'
  package:
    name: '{{ qi_docker_package|default("docker-ce") }}'
    state: present
  become: yes

- name: 'CentOS/RedHat :: start Docker'
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- include: docker-virtualenv.yml
