---
- name: 'create and upgrade the contents of the virtualenv'
  pip:
    virtualenv: '{{ qi_docker_virtualenv }}'
    virtualenv_site_packages: '{{ qi_docker_virtualenv_site_packages }}'
    name:
    - pip
    - distribute
    state: latest
  become: yes

- name: 'install functools32 into the virtualenv'
  pip:
    virtualenv: '/srv/notice/virtualenv'
    virtualenv_site_packages: '{{ qi_docker_virtualenv_site_packages }}'
    name: functools32
  become: yes
  when:
  - ansible_distribution == 'Ubuntu'
  - ansible_distribution_version == '12.04'

- name: 'install docker and docker-compose into the virtualenv'
  pip:
    virtualenv: '{{ qi_docker_virtualenv }}'
    virtualenv_site_packages: '{{ qi_docker_virtualenv_site_packages }}'
    name:
    - '{{ qi_docker_pip_docker_package|default("docker") }}'
    - '{{ qi_docker_pip_docker_compose_package|default("docker-compose") }}'
  become: yes

# NOTE: This is sort of unfortunate but I don't currently have a better
# solution. (You can't use {{}}s to set this in task vars.)
- name: 'use the virtualenv Python interpreter'
  set_fact:
    ansible_python_interpreter: '{{ qi_docker_virtualenv }}/bin/python'
