---
- name: 'set APT priority for Stretch packages'
  copy:
    dest: '/etc/apt/preferences.d/stretch.pref'
    content: |
      Package: *
      Pin: release n=stretch
      Pin-Priority: 100
  become: yes

- name: 'Debian :: add APT repository for Debian Stretch'
  apt_repository:
    repo: 'deb http://httpredir.debian.org/debian stretch main contrib non-free'
  become: yes
  when: ansible_machine != 'armv7l'

- name: 'Raspbian :: add APT repository for Raspbian stretch'
  apt_repository:
    repo: 'deb http://mirrordirector.raspbian.org/raspbian stretch main contrib non-free rpi'
  become: yes
  when: ansible_machine == 'armv7l'
