---
- name: 'Set Journal to not forward logs to syslog'
  ansible.builtin.lineinfile:
    path: '/etc/systemd/journald.conf'
    line: 'ForwardToSyslog=no'
  become: yes
  notify: 'restart_journal'

- meta: 'flush_handlers'

- name: 'start systemd-journal'
  ansible.builtin.service:
    name: 'systemd-journal'
    enabled: yes
    state: 'started'
  become: yes

- name: 'disable rsyslog service'
  ansible.builtin.service:
    name: 'rsyslog'
    enabled: no
  become: yes

- name: 'stop rsyslog service'
  ansible.builtin.service:
    name: 'rsyslog'
    state: 'stopped'
    enabled: no
  become: yes
